# Generated by Django 2.2.6 on 2019-10-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.URLField(max_length=228)),
                ('timeshift', models.DurationField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'URL для парсинга',
                'verbose_name_plural': 'URL для парсинга',
            },
        ),
        migrations.CreateModel(
            name='URLResults',
            fields=[
                ('requested_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_task_app.RequestedURL')),
                ('info', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
